branches:
  only:
    - develop

language: java
dist: trusty

jdk:
  - openjdk14

services:
  - docker


before_script:
  - docker-compose -f postgresd/docker-compose.yml up -d

jobs:
  include:
    - stage: test
      script: mvn test
#    - stage: sonar
#      script: ./mvnw verify sonar:sonar


after_script:
  - docker-compose -f docker/dev/docker-compose.yml stop
  - docker-compose -f docker/dev/docker-compose.yml rm -fyml down
