branches:
  only:
    - develop

language: java
dist: trusty

jdk:
  - openjdk14

services:
  - docker


before_script:
  - docker-compose -f postgresd/docker-compose.yml up -d

jobs:
  include:
    - stage: test
      script: mvn test
    - stage: sonar
      script: mvn verify sonar:sonar
