version: "3.7"

services:
  eureka:
    container_name: eureka
    image: com.sys/eureka:0.0.1
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA=http://eureka:9094/eureka
    depends_on:
      - "config"
    ports:
      - "127.0.0.1:9094:9094"

  zuul:
    container_name: zuul
    image: com.sys/zuul:0.0.1
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA=http://eureka:9094/eureka
    depends_on:
      - "config"
      - "eureka"
    ports:
      - "127.0.0.1:9095:9095"

  postgres:
    container_name: postgres
    image: postgres:12.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: sysreserv
      POSTGRES_PASSWORD: sysreserv
      POSTGRES_DB: usr
    volumes:
      - "./postgresd/init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "127.0.0.1:5432:5432"

  establishment:
    container_name: establishment
    image: com.sys/establishment:0.0.1
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA=http://eureka:9094/eureka
    depends_on:
      - "zuul"
      - "eureka"
      - "postgres"
    ports:
      - "127.0.0.1:9097:9097"